#!/bin/bash
# Script para verificar el estado de la app en el servidor

echo "=== Estado de la Aplicación ==="
echo ""
echo "1. Estado de contenedores Docker:"
docker compose ps 2>/dev/null || echo "Docker no disponible o no está en el directorio correcto"
echo ""
echo "2. Últimos logs de la aplicación (50 líneas):"
docker compose logs --tail=50 app 2>/dev/null || echo "No se pueden obtener logs"
echo ""
echo "3. Verificando puerto 8604:"
netstat -tlnp 2>/dev/null | grep 8604 || ss -tlnp 2>/dev/null | grep 8604 || echo "Puerto no encontrado o comando no disponible"
echo ""
echo "4. Health check:"
curl -s http://localhost:8604/api/health 2>/dev/null || echo "Health check falló"
echo ""
echo "5. Verificando rutas principales:"
echo "  - / : $(curl -s -o /dev/null -w '%{http_code}' http://localhost:8604/ 2>/dev/null || echo 'ERROR')"
echo "  - /api/prompts : $(curl -s -o /dev/null -w '%{http_code}' http://localhost:8604/api/prompts 2>/dev/null || echo 'ERROR')"
